data:
  train_csv: "data/train.csv"
  sample_rate: 16000
  segment_seconds: 4.0


stft:
  n_fft: 512
  hop_length: 128
  win_length: 512


model:
  name: "Conv-TasNet"

  FullSubNet:
    num_freqs: 257
    look_ahead: 2
    sequence_model: "LSTM"
    fb_num_neighbors: 0
    sb_num_neighbors: 15
    fb_output_activate_function: null
    sb_output_activate_function: null
    fb_model_hidden_size: 512
    sb_model_hidden_size: 384
    norm_type: "offline_laplace_norm"
    num_groups_in_drop_band: 2
    weight_init: false

  FullSubNet+:
    num_freqs: 257
    look_ahead: 2
    sequence_model: "LSTM"
    fb_num_neighbors: 0
    sb_num_neighbors: 15
    fb_output_activate_function: null
    sb_output_activate_function: null
    fb_model_hidden_size: 512
    sb_model_hidden_size: 384
    norm_type: "offline_laplace_norm"
    num_groups_in_drop_band: 2
    weight_init: false

  InterSubNet:
    num_freqs: 257
    look_ahead: 2
    sequence_model: "LSTM"
    fb_num_neighbors: 0
    sb_num_neighbors: 15
    fb_output_activate_function: null
    sb_output_activate_function: null
    fb_model_hidden_size: 512
    sb_model_hidden_size: 384
    norm_type: "offline_laplace_norm"
    num_groups_in_drop_band: 2
    weight_init: false

  Conv-TasNet:
    N: 512        
    L: 16          
    B: 128     
    H: 512         
    P: 3        
    X: 8        
    R: 3           
    norm_type: "gLN" 
    mask_act: "relu" 

  

train:
  batch_size: 8
  num_workers: 0
  epochs: 100
  lr: 0.0003
  weight_decay: 0.0
  grad_clip: 5.0
  loss: "sisnr"
  early_stop_patience: 15
  device: "auto"
  seed: 42
  log_dir: "runs"
  checkpoint_dir: "checkpoints"


infer:
  device: "auto"

  FullSubNet:
    checkpoint: "checkpoints/FullSubNet_EN.tar"

  FullSubNet+:
    checkpoint: "checkpoints/FullSubNet+_EN.tar"

  InterSubNet:
    checkpoint: "checkpoints/InterSubNet_EN.tar"

  Conv-TasNet:
    checkpoint: "checkpoints/Conv-TasNet_EN.pt"

  input: null
  output: null

  input_dir: "inputTest"
  output_dir: "output/enhanced"